package br.com.rotaract.secretaria.constant;

public enum AreaEnfoque {
	PAZ_E_RESOLUÇÃO_DE_CONFLITOS,
	DESENVOLVIMENTO_ECONÔMICO_E_COMUNITÁRIO,
	EDUCAÇÃO_BÁSICA_E_ALFABETIZAÇÃO,
	ÁGUA_E_SANEAMENTO,
	PREVENÇÃO_E_TRATAMENTO_DE_DOENÇAS,
	SAÚDE_MATERNO_INFANTIL,
	APOIO_AO_MEIO_AMBIENTE
	
}
